#cloud-config
hostname: dev

# Update and upgrade
package_update: true
package_upgrade: true

# Packages
packages:
 - curl
 - wget
 - git
 - lua5.3
 - default-jre
 - python3
 - tmux
 - htop
 - fzf
 - autojump
 - software-properties-common
 - gcc
 - gdb
 - vite
 - npm
 - neovim

# PPAs
apt:
  sources:
    ignored1: # this name is irrelevant?
      source: "ppa:neovim-ppa/unstable"


# Users
users:
  - name: sixsa
    gecos: Dalton Luce
    groups: [sudo]
    shell: /bin/bash

# Commands
runcmd:
  - npm install n -g && n latest # install latest version of nodejs