"""Commit-message and branch-history checks."""

from __future__ import annotations

import re
from pathlib import Path

from databricks.git import commit_bodies, commit_messages, merge_commits
from databricks.types import Finding

MODULE = "databricks.commit"

# type(scope): subject  — scope is optional Jira key or short name
CONVENTIONAL_COMMIT = re.compile(
    r"^(feat|fix|refactor|test|docs|chore|style|perf|ci|build|revert)"
    r"(\([A-Za-z][A-Za-z0-9_-]*\))?: .+"
)

AI_ATTRIBUTION = re.compile(
    r"(?i)(co-authored-by:|generated by|anthropic|openai|claude|codex|cursor agent)"
)


def check_conventional_commits(base_ref: str, cwd: Path | None = None) -> list[Finding]:
    findings: list[Finding] = []
    for _sha, subject in commit_messages(base_ref, cwd=cwd):
        if CONVENTIONAL_COMMIT.match(subject):
            continue
        findings.append(
            Finding(
                rule="conventional_commit_format",
                file="",
                line=None,
                severity="warn",
                message=f'commit subject does not match conventional format: "{subject}"',
                module=MODULE,
            )
        )
    return findings


def check_merge_commits(base_ref: str, cwd: Path | None = None) -> list[Finding]:
    findings: list[Finding] = []
    for sha, subject in merge_commits(base_ref, cwd=cwd):
        short = sha[:8]
        findings.append(
            Finding(
                rule="merge_commit_in_stack",
                file="",
                line=None,
                severity="warn",
                message=f"merge commit {short} in stack: {subject}",
                module=MODULE,
            )
        )
    return findings


def check_ai_attribution(base_ref: str, cwd: Path | None = None) -> list[Finding]:
    findings: list[Finding] = []
    for sha, body in commit_bodies(base_ref, cwd=cwd):
        if not AI_ATTRIBUTION.search(body):
            continue
        short = sha[:8]
        findings.append(
            Finding(
                rule="ai_attribution_in_commit",
                file="",
                line=None,
                severity="error",
                message=f"commit {short} contains Co-authored-by or AI attribution",
                module=MODULE,
            )
        )
    return findings


def run(base_ref: str, cwd: Path | None = None) -> list[Finding]:
    return [
        *check_conventional_commits(base_ref, cwd=cwd),
        *check_merge_commits(base_ref, cwd=cwd),
        *check_ai_attribution(base_ref, cwd=cwd),
    ]
