#!/bin/sh

# Used by the OS-specific case below.
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
KERNEL="$(uname -r | tr '[:upper:]' '[:lower:]')"

alias l='eza -l --no-permissions --no-user --no-filesize'
alias la='eza -l'

alias rv='docker run -i --rm -v "$PWD":/root ghcr.io/shouxulin/cs4414hw1'

alias f='fzf --preview "head -\$LINES {}"'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'

alias ece='source $HOME/.dotfiles/scripts/ece.sh; connect'
alias vpn='source $HOME/.dotfiles/scripts/ece.sh; connect_to_vpn'

alias pdf='pandoc -f markdown-implicit_figures --columns=80 --wrap=auto -o'

alias stat='git status'
alias com='git commit -m'

alias dot='cd $HOME/.dotfiles'

alias lab='/opt/homebrew/opt/jupyterlab/bin/jupyter-lab'

alias v='nvim'

alias nav='docker-compose run --rm nav'
alias autobike='docker run -it --rm -v "$(pwd):/usr/app" --user root --env DISPLAY=host.docker.internal:0 autobike'

# OS specific aliases
case $OS in

    # linux
    linux*)
        
        case $KERNEL in
            # WSL
            *microsoft*)
                alias windows='cd /mnt/c/Users/sixsa/';;
        
             # Normal, good ol' linux
            *)
                : ;;
        esac
        ;;

    # Mac OSX
    darwin*)
        alias vm="multipass"
        # Connect to Arca and attach the shared 'main' tmux session (create if absent)
        alias arcat='arca et -- tmux new-session -A -s main'
        ;;

    # Cygwin
    cygwin*)
        ;;
    
    # MinGW
    msys*)
        ;;

    # Other
    *)
        ;;
esac

