#!/bin/sh

# Reset path so it does not get longer each time this is sourced (Mac OSX
# sources .profile on every new terminal, so this is desirable)
PATH=$(getconf PATH);

PATH="/usr/local/anaconda3/bin:$PATH"           # anaconda
PATH="/opt/homebrew/anaconda3/bin:$PATH"

case $OS in

    # linux
    linux*)
        PATH="/usr/local/bin:$PATH" # starship
        ;;

    # Mac OSX
    darwin*)
        PATH="/usr/local/bin:$PATH"         # ???
        PATH="/opt/homebrew/bin:$PATH"      # homebrew executable
        PATH="/Library/TeX/texbin:$PATH"    # LaTeX bins

        ;;
    # Cygwin
    cygwin*)
        ;;

    # MinGW
    msys*)
        ;;

    # Other
    *)
        ;;
esac

export PATH;
