#!/bin/sh

# General .rc file for interactive shells

# If not running interactively, don't do anything
case $- in
    *i*);;      # interactive
    *) return;; # script
esac

# Aliases (broken into own file as it has OS specific stuff)
if [ -f "$HOME/.shell/alias" ]; then
    . "$HOME/.shell/alias"
fi

# Source other stuff (broken into own file as it has OS specific stuff)
if [ -f "$HOME/.shell/source" ]; then
    . "$HOME/.shell/source"
fi

# For Xquartz
if command -v xhost &> /dev/null
then
  xhost +localhost
fi


# fancy prompt with starship
eval "$(starship init "$SHELL")"

# Something homebrew related
eval "$(/opt/homebrew/bin/brew shellenv)"

# Initialize Midway environment and establish secure session
echo "Starting Midway Secure Session Initialization..."
echo "Please wait while the environment is being set up..."

# Run the mwinit command to establish the session
mwinit -o -s