#!/bin/sh

safe_source() {
    if [ -f "$1" ]; then
        . "$1"
    else
        echo "Warning: File $1 not found"
    fi
}

safe_source /Users/daluce/.brazil_completion/bash_completion # Amazon Brazil source?
safe_source "$HOME/.cargo/env"

# Source OS dependant locations
case $OS in

    # linux
    linux*)
        safe_source /usr/share/autojump/autojump.sh
        ;;

    # Mac OSX
    darwin*)
        safe_source /opt/homebrew/etc/profile.d/autojump.sh
        ;;

    # Cygwin
    cygwin*)
        ;;

    # MinGW
    msys*)
        ;;

    # Other
    *)
        ;;
esac